import type { Metadata } from 'next'
import '@/styles/globals.css'
import { SideBar } from '@/components/global/sideBar'
import { Header } from '@/components/global/header'
import { NotificationProvider } from '@/contexts/NotificationContext'

export const metadata: Metadata = {
  title: 'Task Flow App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <NotificationProvider>
        <div className="flex flex-row w-screen h-screen overflow-hidden ">
          <SideBar />
          <div className="flex-1 flex flex-col">
            <Header />
            <div className="flex-1 min-h-0 overflow-auto scrollbar-thin scrollbar-track-light scrollbar-thumb-accent">
              {children}
            </div>
          </div>
        </div>
      </NotificationProvider>
    </>
  )
}
