import type { Metadata } from 'next'
import '@/styles/globals.css'

import { ProjectList } from '@/components/pages/tasks/projects'
import { prisma } from '@/lib/prisma'

export const metadata: Metadata = {
  title: 'Task Flow App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const projects = await prisma.project.findMany({})
  return (
    <div className="grid grid-cols-12 gap-2 p-2">
      <ProjectList projects={projects} />
      <div className="col-span-9 border h-screen">{children}</div>
    </div>
  )
}
